### ISSUE TITLE
Serializer,  DISJ2, DISJMapRed

### ISSUE THREAD

**Issue by sashank** [orochi89/Clusion#1]
Am trying to create a pom file and add maven dependencies to make the project easy to build and use. Currently stuck in identifying the package behind "Serializer",  DISJ2, DISJMapRed classes being used inside IEX2LevAMAZON class . Any idea from which package these classes are being used from ? 

i can send a pull request once am done with this

**Comment by orochi89** [comment]
Hi sashank, thanks for your comment. I have added the Serializer class that was missing. It serializes/de-serializes byte arrays. For DISJ2 and DISJMapRed, they refer respectively to IEX2Lev and IEX2LevAMAZON classes. I have modified the IEX2LevAMAZON class to reflect these changes.

**Comment by sashank** [comment]
Ok the above are cleared now , but does IEX2LevAMAZON class compile for you ? This below line does not compile 

> MMGlobal.setupSI(CryptoPrimitives.generateCmac(listSK.get(0),token[0]), secondaryLookup.keySet(), secondaryLookup, bigBlock, smallBlock, dataSize);

Because secondaryLookup.keySet() returns a Set and MMGlobal.setupSI expects a String[]

**Comment by sashank** [comment]
Hi Tarik,

I have sent a pull request , simplifing all the dependency management etc.
Its very easy for somebody to download , build and quickly test the package now.

I shall try to make some more changes later , let me know any questions

Regards,
Sashank

**Comment by orochi89** [comment]
Thanks Sashank, I have merged it.

Tarik
