### ISSUE TITLE
Exception because Lucene versions aren't the same

### ISSUE THREAD

**Issue by xytosis** [orochi89/Clusion#3]
The lucene version in the pom.xml is 6.1.0, but the lucene analyzers version is 5.3.1. This seems to compile fine, but when I run the `TestIndexing` class, I get a NoSuchFieldError for some lucene version. Changing both the versions to 6.1.0 seems to fix this issue.

**Comment by orochi89** [comment]
Thank you. We have fixed the version of Lucene to 6.1.0.
