### ISSUE TITLE
Clusion used for encrypted database?

### ISSUE THREAD

**Issue by ihsanhaikalz** [orochi89/Clusion#5]
Can Clusion be used also for encrypted database to add update, edit, delete new entry in the database or do query search for the data stored in the database? You mentioned Clusion can be used for file indexing and querying.

**Comment by orochi89** [comment]
Clusion's class: DynRH2Lev.java handles updates including edit. The actual version does not handle delete, we are working on it and will be available soon. DynRH2Lev.java comes also with a forwrd-secure version. The test class's name is TestLocalDynRH2Lev.java.

We will update the Readme to include the new features.
