### ISSUE TITLE
Running error: jvm heap space/ GC overhead limit exceeded

### ISSUE THREAD

**Issue by loyaltyoffire** [orochi89/Clusion#8]
When I tested the newest program with a big test-dataset(Number of (w, id) pairs 1042890), there are some errors happened. The main-class is TestLocalIEX2Lev, I run the code in eclipse and I allocated -Xms512m
-Xmx2048m memory for jvm. It looks like memory that I allocated is still not enough to use. So could I know your test-dataset scale or maybe some advice.

**Comment by orochi89** [comment]
There are three ways to get around the memory issues that I can think of. The first and trivial solution would be to use a machine with more memory. For our benchmarking for IEX, the experimental evaluation was performed using Amazon EC2 instance c3.8xlarge with 60 GB of RAM. We used the Enron dataset for our evaluation. The second solution would be to introduce some filtering (in our benchmarking we followed the filtering introduced in the IEX paper). The filtering, at a higher level, will save space while not impacting communication overhead that much. You can think of it as a possible tradeoff. The third solution, which will be harder to put on place, is to write to disk all the encrypted data structure outputted by the IEX setup algorithm. In this case, as long as you have enough space on disk, that would be fine. However, in this case, you need to perform some changes to the code that are not necessarily trivial.
